### ISSUE TITLE
not able to deploy to heroku

### ISSUE THREAD

**Issue by Aman-design** [reacherhq/backend#237]
respected i am trying to deploy backend part directly to heroku but i am geeting application error what should i do ?

**Comment by amaurym** [comment]
I'm not sure it could be a ton of reasons. Do you have some logs?

**Comment by ribonred** [comment]
i have same problem

here is the log


`2022-01-30T16:16:09.133654+00:00 app[web.1]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', src/bin/heroku.rs:41:44
2022-01-30T16:16:09.133677+00:00 app[web.1]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-01-30T16:16:09.266886+00:00 heroku[web.1]: Process exited with status 101
2022-01-30T16:16:09.323167+00:00 heroku[web.1]: State changed from starting to crashed
2022-01-30T16:16:09.328675+00:00 heroku[web.1]: State changed from crashed to starting
2022-01-30T16:16:09.769903+00:00 heroku[web.1]: Starting process with command `./target/release/heroku`
2022-01-30T16:16:10.623423+00:00 app[web.1]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', src/bin/heroku.rs:41:44
2022-01-30T16:16:10.623436+00:00 app[web.1]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-01-30T16:16:10.724280+00:00 heroku[web.1]: Process exited with status 101
2022-01-30T16:16:10.785006+00:00 heroku[web.1]: State changed from starting to crashed`

**Comment by amaurym** [comment]
@ribonred Can you try again with the deploy button on the README? I changed to deploy the 0.3.12 tag instead of master, as master currently has some WIP changes related to bulk verification.

**Comment by ribonred** [comment]
> @ribonred Can you try again with the deploy button on the README? I changed to deploy the 0.3.12 tag instead of master, as master currently has some WIP changes related to bulk verification.

nvm.. heroku blocked port 25 cant validate gmail account.. so i use digital ocean.. work perfectly👍

**Comment by ribonred** [comment]
@amaurym you can request to them.. they have limited request tho.. and what purpose you want to open that port.. another easy one is alibaba.. still request.. but auto review.. no need email to support https://www.alibabacloud.com/help/en/doc-detail/56130.htm took me an hour or so..

i heard contabo by default port 25 is open.. not try that yet

https://contabo.com/en/vps/?utm_source=cj&utm_medium=affiliate&utm_campaign=vps&source=affiliate&AID=12454632&PID=8052621&SID=&CJEVENT=f32c47e182b111ec811004630a180513
